### PR TITLE
document using latest zk

### PR DESCRIPTION
**Pull request by epugh**
I wanted to share what I learned in bumping to Solr 8.7 and the latest ZK for the next person ;-).  Please do review that the changes I made are "right".

### CODE REVIEW

**Comment by makuk66** [comment]
The `0.0.0.0` ones were there on purpose. I don't recall what purpose exactly... is it that without it, they do not listen on localhost? Not sure if any of the scripts/code cares, or if the idea was that you could run `zkCli.sh` from a `docker exec`.

Update: I tested, and both startup and `zkCli.sh` seemed fine. Dunno

**Comment by epugh** [comment]
I gave it a stab of putting back the 0.0.0.0, and this is what Solr is giving me now:

Screenshot at Nov 11 11-47-02

I removed the `0.0.0.0` and Solr became happy again:

Screenshot at Nov 11 11-53-29


Also, I think that run `zkCli.sh` is kind of devops smell, since we do have our `bin/solr zk` method, as well as the evolving APIs, like the configset api, to reduce the need to do `zkCli.sh`.

**Comment by makuk66** [comment]
Sounds good to me

**Review by makuk66 — APPROVED** [review]

**Comment by epugh** [comment]
BTW, this has been one of the most useful repos for me to learn more about Solr and Docker!

**Comment by dsmiley** [comment]
Thanks for the contribution.  I tried this out, including access ZK's new prometheus support.

  I didn't know this "docker-solr-examples" repo existed before today, or I forgot about it.  Maybe stuff like this could go right into Solr's `example/` dir?  Any way; such a discussion deserves solr dev list discussion, not hidden here.

**Comment by epugh** [comment]
David, as usual, you think beyond just the immediate ticket.  I agree that once the Docker stuff is in Solr (and it's close!) that moving some of this over and beefing up the ref guide will be a nicely block of work!

**Pull request merged**
